---
version: "3.6"
services:
  jupyterlab:
    build:
      context: .
    image: wangsen992/mpich33_cuda_jupyterlab
    container_name: jupyterlab
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - /mnt/d/docker-repos/Apps/mpich33_jupyterlab/work:/work
      - /mnt/d:/mnt/d
    ports:
      - 8888:8888
    restart: unless-stopped
    command: jupyter-lab --ip=0.0.0.0
