---
version: "3.6"
services:
  jupyterlab:
    build:
      context: ${CONTEXT}
      dockerfile: OS/ubuntu/Dockerfile
      # Base: 
      #   Using ubuntu:devel causes cmake to create error 
      #   Using ubuntu:20.04 causes mpich33 compile error
      args:
        - BASE=tensorflow/tensorflow:2.13.0-gpu-jupyter
        - DI_RESOURCES=Resources
        - IMAGE_RESOURCES=/app/Resources
        - USER=${APP_USER}
        - BRANCH=${OF9_BRANCH}
        - INSTALL_ENV_SCRIPT=/app/Resources/Apps/mpich33_cuda_jupyterlab/env-setup.sh
        - INSTALL_APP_SCRIPT=/app/Resources/Apps/mpich33_cuda_jupyterlab/app-setup.sh
    image: wangsen992/mpich33_cuda_jupyterlab
    container_name: jupyterlab
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - /mnt/d/docker-repos/Apps/mpich33_jupyterlab/work:/work
      - /mnt/d:/mnt/d
    ports:
      - 8888:8888
    restart: unless-stopped
    command: /bin/bash -c ". ~/.bashrc && cd /mnt/d && jupyter-lab --ip=0.0.0.0"
