---
version: "3.6"
services:
  latex:
    build:
      context: /mnt/d/docker-repos/
      dockerfile: OS/ubuntu/Dockerfile
      args:
        - BASE=ubuntu:22.04 # Using devel causes cmake to create error
        - DI_RESOURCES=Resources
        - IMAGE_RESOURCES=/app/Resources
        - USER=wangsen992
        - INSTALL_APP_SCRIPT=
    image: wangsen992/latex
    container_name: latex
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - CONTAINER=latex
    volumes:
      - /mnt/d:/mnt/d
    restart: unless-stopped
    command: sudo tail -F /var/log/*
